# Generated by Django 5.2 on 2025-04-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
